### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by teacher-too** [thierryxing/sentry-beaconfire#1]
kotlin中用`data class`生成的类，怎么使用databing的`@Bindable`注解
我看项目里都是手写getXXX方法，在xml里调用方法的

**Comment by thierryxing** [comment]
我这里使用的是MVVM模式，中间有个ViewModel和Layout进行数据绑定和业务逻辑处理。
而data class生成的全部都是Bean，只提供数据结构，不提过业务逻辑。
所以你说的这种情况我还没有遇到过，建议写个简单的Demo先试试看。

**Comment by teacher-too** [comment]
多谢
测试了，如果数据bean和业务不分开写，好像不可行，用kotlin的set方法，找不到BR.xxx
而且android studio3自带的kotlin与dataBinding互相依赖了😂，
`Circular dependency between the following tasks: `
`:app:compileDebugKotlin`
`\--- :app:dataBindingExportBuildInfoDebug`
`     \--- :app:compileDebugKotlin (*)`

[https://youtrack.jetbrains.com/issue/KT-17936](https://youtrack.jetbrains.com/issue/KT-17936上)也有人提出了这个bug😂，
目测是kotlin插件有问题，换个版本的就ok

**Comment by thierryxing** [comment]
赞！
